Feature/62 uncertainty hazard curve style
GNS-Science/toshi-nest pull request #68
Opened 2022-07-17 21:11 UTC by 0qy

2022-07-17 21:40 UTC, chrisbc reviewed
@0qy  I don't know if it's intentional but the classes and modules names are sometimes plural (hazardCurvesXxxx) and sometimes singular (hazardCurveXxxx). I find this confusing and wonder if we can just make everything singular?

2022-07-17 21:53 UTC, chrisbc commented on src/HazardCurvesUncertainty/HazardCurvesUncertainty.tsx
>  const HazardCurvesUncertianty: React.FC<HazardCurvesUncertaintyProps> = (props: HazardCurvesUncertaintyProps) => {
@0qy misspelling  => HazardCurvesUncertianty

2022-07-17 21:54 UTC, chrisbc requested changes
typo  HazardCurvesUncertianty

2022-07-18 22:05 UTC, chrisbc approved these changes

2022-07-18 22:19 UTC, chrisdicaprio approved these changes

2022-07-18 22:28 UTC, merged